CREATE TABLE CONFIG (
	NOME varchar(40) NOT NULL,
	TITULO varchar(100) NOT NULL,
	CELULAR varchar(100) NOT NULL,
	GRUPOS varchar(100) NOT NULL,
	CONTATO varchar(100) NOT NULL,
	PRECO BOOLEAN DEFAULT FALSE,
	EMAIL varchar(200) NOT NULL
);

CREATE TABLE GRUPO(
	ID bigserial primary key,
	ORDEM INTEGER,
	NOME varchar(200) NOT NULL
);

CREATE TABLE IMAGEM (
	ID BIGSERIAL PRIMARY KEY,
	NOME varchar(100),
	FILE varchar(500) NOT NULL,
	PRECO REAL DEFAULT 0.0,
	ID_GRUPO INTEGER REFERENCES GRUPO(ID),
	PRINCIPAL BOOLEAN DEFAULT FALSE
);


--Criado a estrutura

INSERT INTO CONFIG
VALUES('Lu Fernandes', 'Doces Artesanais e Bolos Caseiros', '(11) 972668404 / 4587-9481', 'Ótimos momentos com detalhes especiais', 'Entre em contato', FALSE, 'lufernand@hotmail.com');

SELECT * FROM CONFIG;

INSERT INTO GRUPO (ORDEM, NOME)
VALUES(1, 'Bolos');

INSERT INTO GRUPO (ORDEM, NOME)
VALUES(2, 'Lembranças');

INSERT INTO GRUPO (ORDEM, NOME)
VALUES(3, 'Casamentos');

INSERT INTO GRUPO (ORDEM, NOME)
VALUES(4, 'Doces Artesanais');

SELECT * FROM GRUPO;









/*
INSERT INTO IMAGEM (NOME, CAMINHO, PRECO)
VALUES ('Cento de brigadeiro', '/images/todas/1.jpg', 39.99);

INSERT INTO IMAGEM (NOME, CAMINHO, PRECO)
VALUES ('Bolo grande', '/images/todas/2.jpg', 69.99);

INSERT INTO IMAGEM (NOME, CAMINHO, PRECO)
VALUES ('Cento de brigadeiro', '/images/todas/3.jpg', 39.99);

INSERT INTO IMAGEM (NOME, CAMINHO, PRECO)
VALUES ('Bolo grande', '/images/todas/4.jpg', 69.99);

INSERT INTO IMAGEM (NOME, CAMINHO, PRECO)
VALUES ('Cento de brigadeiro', '/images/todas/5.jpg', 39.99);

INSERT INTO IMAGEM (NOME, CAMINHO, PRECO)
VALUES ('Bolo grande', '/images/todas/6.jpg', 69.99);

INSERT INTO IMAGEM (NOME, CAMINHO, PRECO)
VALUES ('Cento de brigadeiro', '/images/todas/7.jpg', 39.99);

INSERT INTO IMAGEM (NOME, CAMINHO, PRECO)
VALUES ('Bolo grande', '/images/todas/8.jpg', 69.99);

SELECT * FROM IMAGEM;

INSERT INTO IMAGEM_AGRUPA (ID_GRUPO, ID_IMAGEM)
VALUES (1, 9);

INSERT INTO IMAGEM_AGRUPA (ID_GRUPO, ID_IMAGEM)
VALUES (2, 10);

INSERT INTO IMAGEM_AGRUPA (ID_GRUPO, ID_IMAGEM)
VALUES (1, 11);

INSERT INTO IMAGEM_AGRUPA (ID_GRUPO, ID_IMAGEM)
VALUES (2, 12);

INSERT INTO IMAGEM_AGRUPA (ID_GRUPO, ID_IMAGEM)
VALUES (3, 13);

INSERT INTO IMAGEM_AGRUPA (ID_GRUPO, ID_IMAGEM)
VALUES (3, 14);

INSERT INTO IMAGEM_AGRUPA (ID_GRUPO, ID_IMAGEM)
VALUES (4, 15);

INSERT INTO IMAGEM_AGRUPA (ID_GRUPO, ID_IMAGEM)
VALUES (4, 16);

SELECT * FROM IMAGEM_AGRUPA;*/